src/Entity/MediaBase.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\HasLifecycleCallbacks()
 */
abstract class MediaBase
{
    /**
     * Set source file
     *
     * @param UploadedFile $sourceFile
     *
     */
    public function setSourceFile(UploadedFile $sourceFile = null)
    {
        $this->sourceFile = $sourceFile;
        if (isset($this->source)) {
            $this->tempSourceFile = $this->source;
            $this->source = null;
        }
    }

    /**
     * Get source file
     *
     * @return null|UploadedFile
     */
    public function getSourceFile(): ?UploadedFile
    {
        return $this->sourceFile;
    }

    /**
     * Get Absoulte Path
     * @return null|string
     */
    public function getSourceAbsolutePath()
    {
        return null === $this->source
            ? null
            : $this->getUploadRootDir() . '/' . $this->source;
    }

    /**
     * Get Header Thumbnail Web path
     * @return null|string
     */
    public function getSourceWebPath()
    {
        return null === $this->source
            ? null
            : $this->getUploadDir() . '/' . $this->source;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__ . '/../../public' . $this->getUploadDir();
    }


    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUploadFiles()
    {
        if (null !== $this->getSourceFile()) {
            $this->source = $this->generateUniqueFileName() . '.' . $this->getSourceFile()->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function uploadFiles()
    {
        if (null !== $this->getSourceFile()) {
            $this->getSourceFile()->move($this->getUploadRootDir(), $this->source);
            if (isset($this->tempSourceFile)) {
                if (file_exists($this->getUploadRootDir() . '/' . $this->tempSourceFile)) {
                    unlink($this->getUploadRootDir() . '/' . $this->tempSourceFile);
                }
                $this->tempSourceFile = null;
            }
            $this->sourceFile = null;
        }
    }

    /**
     * @ORM\PreRemove()
     */
    public function storeFilenameForRemove()
    {
        $this->tempSourceFile = $this->getSourceAbsolutePath();
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUploadedFiles()
    {
        if (isset($this->tempSourceFile)) {
            unlink($this->tempSourceFile);
        }
    }

    /**
     * @Assert\Callback()
     * @param ExecutionContextInterface $context
     */
    public function isFileUploadedOrExists(ExecutionContextInterface $context)
    {
        if (null === $this->source && null === $this->sourceFile)
            $context->buildViolation('This value should not be blank.')
                ->atPath('sourceFile')
                ->addViolation();
    }

    /**
     * @return string
     */
    public function generateUniqueFileName()
    {
        return sha1(uniqid(mt_rand(), true));
    }

}

src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Google\Cloud\Firestore\DocumentReference;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Video extends MediaBase implements AdInterface
{
    const EXTENSION = 'mp4';
    const CONTENT_TYPE = 'video';
    const COLLECTION = 'data-videos';
    const PREFIX = 'VID';

    use AdBaseTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    protected $region;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    protected $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $url;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $downloadUrl;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $source;

    /**
     * @ORM\Column(type="datetime")
     *
     */
    protected $startedAt;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     */
    protected $duration;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank()
     * @Assert\Type(
     *     type="float",
     *     message="The value {{ value }} is not a valid {{ type }}."
     * )
     */
    protected $price;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    protected $firebaseId;

    /**
     * @var UploadedFile
     * @Assert\File(
     *      maxSize="20M",
     *      mimeTypes = {"video/mp4"},
     * )
     */
    protected $sourceFile;

    /**
     * @var string
     */
    protected $tempSourceFile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getDownloadUrl(): ?string
    {
        return $this->downloadUrl;
    }

    public function setDownloadUrl(string $downloadUrl): self
    {
        $this->downloadUrl = $downloadUrl;

        return $this;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function setSource(?string $source): self
    {
        $this->source = $source;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->startedAt;
    }

    public function setStartedAt(\DateTimeInterface $startedAt): self
    {
        $this->startedAt = $startedAt;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFirebaseId(): ?string
    {
        return $this->firebaseId;
    }

    public function setFirebaseId(?string $firebaseId): self
    {
        $this->firebaseId = $firebaseId;

        return $this;
    }

    public function getCode(): ?string
    {
        return sprintf('%s_%s_%s_%s', self::PREFIX, $this->region, $this->duration, $this->category);
    }

    public function getContentType()
    {
        return sprintf('%s/%s', self::CONTENT_TYPE,self::EXTENSION);
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return '/uploads/videos';
    }
}

src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Video;
use App\Enum\CategoryEnum;
use App\Enum\DurationEnum;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('region')
            ->add('category', ChoiceType::class, [
                'required' => true,
                'placeholder' => 'Choose an option',
                'choices' => CategoryEnum::getAvailableCategories(true),
            ])
            ->add('sourceFile', FileType::class, [
                'label' => 'Video source (mp4)',
                'data_class' => null,
                'required' => false,
                'attr' => [
                    'class' => 'image_source',
                    'accept' => sprintf('%s/%s', Video::CONTENT_TYPE, Video::EXTENSION)
                ]
            ])
            ->add('startedAt', DateTimeType::class, [
                'required' => false,
                'empty_data' => null,
                'html5' => false,
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd HH:mm:ss',
                'years' => range(2019, 2022),
                'attr' => [
                    'class' => 'form_datetime'
                ]
            ])
            ->add('duration', ChoiceType::class, [
                'required' => true,
                'choices' => DurationEnum::getAvailableDurations()
            ])
            ->add('price', MoneyType::class, [
                'currency' => 'PLN'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use App\Form\VideoType;
use App\Repository\VideoRepository;
use App\Service\Interfaces\PlaylistCollectionProviderInterface;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityManagerInterface;
use Google\Cloud\Core\Exception\GoogleException;
use Google\Cloud\Firestore\FirestoreClient;
use Google\Cloud\Storage\StorageClient;
use Ramsey\Uuid\Uuid;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/video")
 */
class VideoController extends AbstractController
{
    /**
     * @Route("/", name="video_index", methods={"GET"})
     * @param VideoRepository $videoRepository
     * @return Response
     */
    public function index(VideoRepository $videoRepository): Response
    {
        return $this->render('video/index.html.twig', [
            'videos' => $videoRepository->findBy([], ['id' => Criteria::DESC])
        ]);
    }

    /**
     * @Route("/new", name="video_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $video = new Video();
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($video);
            $entityManager->flush();

            return $this->redirectToRoute('video_index');
        }

        return $this->render('video/new.html.twig', [
            'video' => $video,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="video_show", methods={"GET"})
     * @param Video $video
     * @return Response
     */
    public function show(Video $video): Response
    {
        return $this->render('video/show.html.twig', [
            'video' => $video,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="video_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Video $video
     * @return Response
     */
    public function edit(Request $request, Video $video): Response
    {
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('video_index', [
                'id' => $video->getId(),
            ]);
        }

        return $this->render('video/edit.html.twig', [
            'video' => $video,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="video_delete", methods={"DELETE"})
     * @param Request $request
     * @param Video $video
     * @return Response
     */
    public function delete(Request $request, Video $video): Response
    {
        if ($this->isCsrfTokenValid('delete'.$video->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($video);
            $entityManager->flush();
        }

        return $this->redirectToRoute('video_index');
    }

    /**
     * @Route("/{id}/sync", name="video_sync", methods={"GET"})
     * @param EntityManagerInterface $entityManager
     * @param PlaylistCollectionProviderInterface $playlistCollectionProvider
     * @param Video $video
     * @return Response
     */
    public function sync(EntityManagerInterface $entityManager, PlaylistCollectionProviderInterface $playlistCollectionProvider, Video $video): Response
    {
        try {
//            $expires = new \DateTime(  '+ 10 years');
            $storage = new StorageClient();
            $name = $this->getParameter('bucket_videos_directory') . DIRECTORY_SEPARATOR . $video->getSource();
            $uuid = Uuid::uuid4();
            $bucket = $storage->bucket($this->getParameter('bucket_name'));
            $object = $bucket->upload(fopen($video->getSourceAbsolutePath(), 'r'), [
                'name' => $name,
                'metadata' => [
                    'contentType' => $video->getContentType(),
                    'metadata' => [
                        //https://stackoverflow.com/questions/42956250/get-download-url-from-file-uploaded-with-cloud-functions-for-firebase/56010225#56010225
                        'firebaseStorageDownloadTokens' => $uuid
                    ]
                ]
            ]);

            $bucketUrl = $object->gcsUri();
            $downloadUrl = sprintf("https://firebasestorage.googleapis.com/v0/b/%s/o/%s?alt=media&token=%s", $this->getParameter('bucket_name'), urlencode($name), $uuid);
//            $downloadUrl = $object->signedUrl($expires);

            $firestore = new FirestoreClient();
            $item = $firestore->collection(Video::COLLECTION)->add([
                'url' => $bucketUrl,
                'downloadUrl' => $downloadUrl,
            ]);

            $video
                ->setFirebaseId($item->id())
                ->setDownloadUrl($downloadUrl)
                ->setUrl($bucketUrl);

            $entityManager->persist($video);
            $entityManager->flush();

            $documents = $playlistCollectionProvider->find($video);

            $data = $video->prepareDataForFirebase($item, $documents->size());

            foreach ($documents as $document) {
                $document->reference()->collection('items')->add($data);
            }

        } catch (GoogleException $e) {
            // TODO: exception implementation
        } catch (\Exception $e) {
            // TODO: exception implementation
        }
        
        return $this->redirectToRoute('video_index');
    }
}

templates/video/_delete_form.html.twig
<form method="post" action="{{ path('video_delete', {'id': video.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video.id) }}">
    <a class="btn btn-sm btn-outline-secondary" href="{{ path('video_index') }}" role="button">Back to list</a>
    <a class="btn btn-sm btn-outline-secondary" href="{{ path('video_edit', {'id': video.id}) }}" role="button">Edit</a>
    <button class="btn btn-sm btn-outline-secondary">Delete</button>
</form>

templates/video/_form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/video/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Edit Video{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Edit Video</h1>
        <div class="btn-toolbar mb-4 mb-md-1">
            <div class="btn-group mr-0">
                <a class="btn btn-sm btn-outline-secondary" href="{{ path('video_index') }}" role="button">Back to list</a>
            </div>
        </div>
    </div>

    {{ include('video/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

{% block javascripts %}
    <script>
        $('#image_source').on('change',function(){
            $(this).next('.custom-file-label').html($(this).val());
        });

        $(".form_datetime").datetimepicker({
            format: 'yyyy-mm-dd hh:ii:ss',
            autoclose: true,
            minuteStep: 30
        });
    </script>
{% endblock %}

templates/video/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Videos{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Videos</h1>
        <div class="btn-toolbar mb-4 mb-md-1">
            <div class="btn-group mr-0">
                {% if is_granted('ROLE_SUPER_ADMIN') %}
                    <a class="btn btn-sm btn-danger" href="{{ path('collection_remove', {'name': 'video'}) }}" role="button" onclick="return confirm('Warning!!! Are you sure you want to delete this collection?');">Remove collection</a>
                {% endif %}
                <a class="btn btn-sm btn-outline-secondary" href="{{ path('video_new') }}" role="button">Create new item</a>
            </div>
        </div>
    </div>

    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Code</th>
                <th>Firebase Id</th>
                <th class="tb_action_bar">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for video in videos %}
            <tr>
                <td>{{ video.id }}</td>
                <td class="myad-code">{{ video.code }}</td>
                <td>{{ video.firebaseId }}</td>
                <td>
                    {% include 'includes/actions.html.twig' with {'obj': video, 'prefix': 'video', 'syncLabel': 'distribute'} %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

templates/video/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %}New Video{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Create new Video</h1>
        <div class="btn-toolbar mb-4 mb-md-1">
            <div class="btn-group mr-0">
                <a class="btn btn-sm btn-outline-secondary" href="{{ path('video_index') }}" role="button">Back to list</a>
            </div>
        </div>
    </div>
    {{ include('video/_form.html.twig') }}
{% endblock %}

templates/video/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Show Video{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Show Video</h1>
        <div class="btn-toolbar mb-4 mb-md-1">
            <div class="btn-group mr-0">
                {{ include('video/_delete_form.html.twig') }}
            </div>
        </div>
    </div>

    <table class="table table-borderless">
        <tbody>
        <tr>
            <th scope="row" style="width: 20%">Region</th>
            <td>{{ video.region }}</td>
        </tr>
        <tr>
            <th>Category</th>
            <td>{{ video.category }}</td>
        </tr>
        <tr>
            <th>Image source</th>
            <td>
                <div>
                    <figure class="figure">
                        <video width="320" height="240" controls>
                            <source src="{{ asset(video.sourceWebPath) }}" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                        <figcaption class="figure-caption">
                            <a href="{{ asset(video.sourceWebPath) }}" target="_blank">Show original file</a>
                        </figcaption>
                    </figure>
                </div>
            </td>
        </tr>
        <tr>
            <th>Started At</th>
            <td>{{ video.startedAt ? video.startedAt|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Duration</th>
            <td>
                {% transchoice video.duration %}
                    {1} %count% day|]1,Inf[ %count% days
                {% endtranschoice %}
            </td>
        </tr>
        <tr>
            <th scope="row">Price</th>
            <td>{{ video.price|number_format }} PLN</td>
        </tr>
        <tr>
            <th>Firebase Id</th>
            <td>{{ video.firebaseId|default('empty') }}</td>
        </tr>
        <tr>
            <th>Url</th>
            <td>{{ video.url|default('empty') }}</td>
        </tr>
        <tr>
            <th>Download url</th>
            <td>{{ video.downloadUrl|default('empty') }}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}